### ISSUE TITLE
Introduce a way to print to the screen

### ISSUE THREAD

**Issue by Elekrisk** [INDAPlus20/brynolv-evper-ofjall-project#13]
We need to be able to print stuff to the screen.
This would initially only be used for debug messages, and would not need all the functions necessary for the full project.

There is a great chapter on this on [this rust tutorial](https://os.phil-opp.com/vga-text-mode/).

**Comment by brynolv** [comment]
Due to the new version of the bootloader (see #12) it would, the VGA text buffer is o longer usable, instead we need to use a pixel buffer. Joy.
